// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { Navbar } from "@/components/custom/navbar";
import { ChefHat } from "lucide-react";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chef IA - Receitas Inteligentes",
  description: "Reconhecimento de alimentos por imagem e geração de receitas personalizadas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* Header Global */}
          <header className="border-b bg-white/70 dark:bg-gray-900/70 backdrop-blur-sm sticky top-0 z-50 shadow-sm">
            <div className="container mx-auto px-4 py-2.5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="bg-gradient-to-br from-orange-400 to-pink-600 p-2 rounded-xl shadow-md">
                    <ChefHat className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h1 className="text-xl md:text-2xl font-bold bg-gradient-to-r from-orange-600 to-pink-600 bg-clip-text text-transparent">
                      Chef IA
                    </h1>
                    <p className="text-[10px] text-gray-500 dark:text-gray-400 font-medium">
                      Receitas inteligentes
                    </p>
                  </div>
                </div>
                
                <Navbar />
              </div>
            </div>
          </header>

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
